build_targets:
- commands:
  - ci/./build-pitest.sh
  - ci/./run-single-module-mutation-tests.sh ogham-test-utils gregor
  - ci/./run-single-module-mutation-tests.sh ogham-core gregor
  - ci/./run-single-module-mutation-tests.sh ogham-template-thymeleaf-common gregor
  - ci/./run-single-module-mutation-tests.sh ogham-template-freemarker gregor
  - ci/./run-single-module-mutation-tests.sh ogham-email-sendgrid-v2 gregor
  - ci/./run-single-module-mutation-tests.sh ogham-email-sendgrid-v4 gregor
  - ci/./run-single-module-mutation-tests.sh ogham-sms-ovh gregor
  - ci/./run-single-module-mutation-tests.sh ogham-sms-smsglobal gregor
  - ci/./run-single-module-mutation-tests.sh ogham-spring-boot-v1-autoconfigure gregor
  - ci/./run-single-module-mutation-tests.sh ogham-spring-boot-v2-autoconfigure gregor
  - ci/./generate-documentation.sh
  container:
    image: yourbase/yb_ubuntu:18.04
  name: default

ci:
  builds:
  - build_target: default
    name: default
dependencies:
  build:
  - java:11.0.6
  - maven:3.6.3
